### ISSUE TITLE
Update my profile damienbod.com

### ISSUE THREAD

**Issue by damienbod** [merill/bluesky#1049]
### Bug details

Hi Merill I updated my profile link from **damienbod.bsky.social** to **damienbod.com**

https://bsky.app/profile/damienbod.com

Do I need to change something here?

Thanks for this repo, really cool.

Greetings Damien

**Comment by merill** [comment]
@damienbod 

Please use the updated site at https://bluesky.ms and register yourself and do the verification. Thanks!
