### ISSUE TITLE
New Bluesky user

### ISSUE THREAD

**Issue by mmeggmegan** [merill/bluesky#1074]
### Title

Megan Gremmell

### Bluesky profile url

https://bsky.app/profile/mmeggremm.bsky.social

### Twitter profile (url or username)

https://x.com/megahoch

### Category

windows365

### Type

microsoft

**Comment by mmeggmegan** [comment]
HI- I don't see the tag. Did I do something wrong? Or is that a different action?

**Comment by merill** [comment]
This is the old process that is no longer used. Register at https://bluesky.ms and add Connect & Verify your account from there.

**Comment by mmeggmegan** [comment]
[like]  Megan Gremmell reacted to your message:
________________________________
