### ISSUE TITLE
Add Bluesky user VincentH.NET (MVP)

### ISSUE THREAD

**Issue by VincentH-Net** [merill/bluesky#1116]
Please add me for MVP label. Thanks!

https://bsky.app/profile/vincenth.net

Above Bsky link is also on my MVP profile:

https://mvp.microsoft.com/en-US/MVP/profile/751bf84a-ef18-eb11-a813-000d3a8dfe0d

**Comment by merill** [comment]
@VincentH-Net Please use the updated site at https://bluesky.ms and register yourself and do the verification. Thanks!
