### ISSUE TITLE
[Bug] I don't show up on bluesky.ms

### ISSUE THREAD

**Issue by patriksvensson** [merill/bluesky#1117]
### Bug details

I'm in the configuration (https://github.com/merill/bluesky/blob/main/website/config/patriksvensson.se.json), but I don't show up on the website.

**Comment by merill** [comment]
@patriksvensson There is a new version of the site which no longer uses the GitHub repo. You can directly register at https://bluesky.ms after signing in.

**Comment by patriksvensson** [comment]
Ah 👍 Might be a good idea to update the `README.md` and remove the configuration then, to avoid further confusion.
