### ISSUE TITLE
[Bug] Error: User has not verified their email

### ISSUE THREAD

**Issue by NKarolak** [merill/bluesky#1118]
### Bug details

I've just registered, verified my email by clicking on the mail link, connected my Bsky profile, entered what I post about... All fine.

But when I try to verify that I'm an MVP (https://mvp.microsoft.com/en-us/MVP/profile/0789d8ed-d3d1-480b-9fee-5bc01628baa2), it keeps saying "Error: User has not verified their email".
Could it be related to that my email address countains a "+"?

**Comment by NKarolak** [comment]
Solved by visiting the homepage again, then Register, then Sign in. 
Although I was signed in all the time to enter my data 🤷🏻‍♀️

**Comment by merill** [comment]
Thanks @NKarolak 

There was a related issue that others saw too and I was able to get to the bottom of it and fix it.
