### ISSUE TITLE
[Bug][POST] "/api/demo/blueskyProfiles/check-ownership": 401

### ISSUE THREAD

**Issue by KirillOsenkov** [merill/bluesky#1125]
### Bug details

![image](https://github.com/user-attachments/assets/87e4e976-7540-4358-bc30-211eb8cee1eb)

On [link](https://bluesky.ms/dashboard/linkverify) after I fill out the form I get a 401:

![image](https://github.com/user-attachments/assets/2b002759-38ec-4cac-9423-92b85978f916)

![image](https://github.com/user-attachments/assets/42493d29-6567-484f-9b54-bd632e592f9a)

**Comment by KirillOsenkov** [comment]
I tried that, still got a 401 :|

**Comment by merill** [comment]
It all looks good. Can you retry with a new app password?

**Comment by KirillOsenkov** [comment]
Yup, tried with a new app password and it worked! Thanks!
