### ISSUE TITLE
Missing JavaScript-related topics

### ISSUE THREAD

**Issue by manekinekko** [merill/bluesky#1127]
### Bug details

Hi, fellow FTE here 👋

I appreciate the time and effort you are putting into building this platform! Thank you ❤️

While selecting the topics I write about, I could not find those related to my work. May I request adding:
- Developer - JavaScript
- Developer - Node.js
- Developer - WebAssembly

![image](https://github.com/user-attachments/assets/ba49f6c1-f4b3-45ab-90aa-ae91a571ed1b)

**Comment by merill** [comment]
Done! 

Thanks for requesting @manekinekko
