### ISSUE TITLE
New Bluesky user

### ISSUE THREAD

**Issue by Steve-Fenton** [merill/bluesky#372]
Hey!

I'm now on Bluesky.

https://bsky.app/profile/stevefenton.co.uk

I'm a Microsoft MVP and a long-time developer technologies user from the "developer, developer, developer" era.

I have rel=me backlinks on my website to validate that my social accounts are me!

Thanks for providing this list! 

Steve

**Comment by merill** [comment]
Done. Added.

**Comment by Steve-Fenton** [comment]
Amazing! Thank you.
