### ISSUE TITLE
AkaUtils missing Get-AkaLongUrl function

### ISSUE THREAD

**Issue by SamErde** [merill/bluesky#6]
After submitting an issue, I noticed that the [add-link.yaml](https://github.com/merill/bluesky/actions/workflows/add-link.yaml) workflow failed with this error: 

```powershell
New-AkaLinkFromIssue: /home/runner/work/bluesky/bluesky/build/scripts/AkaUtils.ps1:220
Line |
 220 |          New-AkaLinkFromIssue -issue $issue -isUpdateGitHubIssue $true …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AkaLongUrl' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the spelling of the
     | name, or if a path was included, verify that the path is correct and try
     | again.
```
It looks like your copy of **AkaUtils** in this repository is not current with the [AkaUtils in the aka repository](https://github.com/merill/aka/blame/main/build/scripts/AkaUtils.ps1#L78). This repo is [missing the Get-AkaLongUrl function in that file](https://github.com/merill/bluesky/blob/9b6d26ade4a9003aa714731471bd6863f5124b06/build/scripts/AkaUtils.ps1#L165).

**Comment by merill** [comment]
Dude, I'm still building it 😂

**Comment by merill** [comment]
But yes thanks, will fix it.

**Comment by SamErde** [comment]
Hehe, sorry, I know! Just figured I'd post in case you hadn't seen that yet. It has been a [quasi] pair-programming kind of day today. 🙂

**Comment by merill** [comment]
Thank you for submitting https://bsky.app/profile/|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~. Unfortunately the link is not a valid Bluesky link. If this is an error, please try submitting the form again. If it is not resolved please reach out to me at https://bsky.app/profile/merill.net and let me know. Thanks!
